### ISSUE TITLE
[camel-main] Openapi-java native is not working (CAMEL-18963)

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4900]
Change in Camel (https://issues.apache.org/jira/browse/CAMEL-18963) brought different openapi implementation.
Compilation and JVM is working fine (after smaller fixes). Native fails with:

```
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.util.JapaneseImperialCalendar is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
```

(With a very brute fix native tests proceed but several tests fail. I'm not sure whether it is related to the brute fix or not.
Fix:

```
@TargetClass(Calendar.Builder.class)
final class CalendarBuilderSubstitution {
    @Substitute
    public Calendar build() {
        throw new UnsupportedOperationException("Calendar::build is not supported");
    }
}
```

**Comment by JiriOndrusek** [comment]
Failed tests in native mode:

```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   OpenApiV2IT>OpenApiTest.invokeApiDocumentEndpoint:66 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV2IT>OpenApiV2Test.openApiBasicAuthSecurityDefinition:80 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV2IT>OpenApiV2Test.openApiDefinitions:147 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV2IT>OpenApiV2Test.openApiDefinition:132 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV2IT>OpenApiTest.openApiEndpointSecurity:81 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV2IT>OpenApiTest.openApiInfoSpecification:177 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV2IT>OpenApiV2Test.openApiKeySecurityDefinition:96 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV2IT>OpenApiV2Test.openApiOauth2SecurityDefinition:114 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV2IT>OpenApiV2Test.openApiOperationSpecification:48 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV2IT>OpenApiTest.openApiVendorExtensions:198 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV2IT>OpenApiTest.testCORSHeaders:208 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR] Errors: 
[ERROR]   OpenApiV2IT>OpenApiTest.invokeApiDocumentEndpoint:63 » IllegalState Failed to ...
[ERROR]   OpenApiV2IT>OpenApiV2Test.openApiBasicAuthSecurityDefinition:77 » IllegalState
[ERROR]   OpenApiV2IT>OpenApiV2Test.openApiDefinitions:144 » IllegalState Failed to conv...
[ERROR]   OpenApiV2IT>OpenApiV2Test.openApiDefinition:129 » IllegalState Failed to conve...
[ERROR]   OpenApiV2IT>OpenApiTest.openApiEndpointSecurity:78 » IllegalState Failed to co...
[ERROR]   OpenApiV2IT>OpenApiTest.openApiInfoSpecification:174 » IllegalState Failed to ...
[ERROR]   OpenApiV2IT>OpenApiV2Test.openApiKeySecurityDefinition:93 » IllegalState Faile...
[ERROR]   OpenApiV2IT>OpenApiV2Test.openApiOauth2SecurityDefinition:111 » IllegalState F...
[ERROR]   OpenApiV2IT>OpenApiV2Test.openApiOperationSpecification:45 » IllegalState Fail...
[ERROR]   OpenApiV2IT>OpenApiTest.openApiVendorExtensions:195 » IllegalState Failed to c...
[INFO] 
[ERROR] Tests run: 23, Failures: 11, Errors: 10, Skipped: 1



[ERROR] Failures: 
[ERROR]   OpenApiV3IT>OpenApiTest.invokeApiDocumentEndpoint:66 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiAllOf:150 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiAnyOf:167 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiTest.openApiBasicAuthSecurityDefinition:114 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiBearerAuthSecurityDefinition:46 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiComponents:104 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiTest.openApiEndpointSecurity:81 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiTest.openApiInfoSpecification:177 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiTest.openApiKeySecurityDefinition:96 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiMutualTlsSecurityDefinition:62 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiTest.openApiOauth2SecurityDefinition:131 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiOneOf:120 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiOpenIdSecurityDefinition:76 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiTest.openApiOperationSpecification:149 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiServers:92 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiTest.openApiVendorExtensions:198 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR]   OpenApiV3IT>OpenApiTest.testCORSHeaders:208 1 expectation failed.
Expected status code <200> but was <204>.

[ERROR] Errors: 
[ERROR]   OpenApiV3IT>OpenApiTest.invokeApiDocumentEndpoint:63 » IllegalState Failed to ...
[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiAllOf:147 » IllegalState Failed to convert th...
[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiAnyOf:164 » IllegalState Failed to convert th...
[ERROR]   OpenApiV3IT>OpenApiTest.openApiBasicAuthSecurityDefinition:111 » IllegalState ...
[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiBearerAuthSecurityDefinition:43 » IllegalState
[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiComponents:101 » IllegalState Failed to conve...
[ERROR]   OpenApiV3IT>OpenApiTest.openApiEndpointSecurity:78 » IllegalState Failed to co...
[ERROR]   OpenApiV3IT>OpenApiTest.openApiInfoSpecification:174 » IllegalState Failed to ...
[ERROR]   OpenApiV3IT>OpenApiTest.openApiKeySecurityDefinition:93 » IllegalState Failed ...
[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiMutualTlsSecurityDefinition:59 » IllegalState
[ERROR]   OpenApiV3IT>OpenApiTest.openApiOauth2SecurityDefinition:128 » IllegalState Fai...
[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiOneOf:117 » IllegalState Failed to convert th...
[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiOpenIdSecurityDefinition:73 » IllegalState Fa...
[ERROR]   OpenApiV3IT>OpenApiTest.openApiOperationSpecification:146 » IllegalState Faile...
[ERROR]   OpenApiV3IT>OpenApiV3Test.openApiServers:89 » IllegalState Failed to convert t...
[ERROR]   OpenApiV3IT>OpenApiTest.openApiVendorExtensions:195 » IllegalState Failed to c...
[INFO] 
[ERROR] Tests run: 35, Failures: 17, Errors: 16, Skipped: 1

```

**Comment by JiriOndrusek** [comment]
Fixed in camel-main

**Comment by raweber42** [comment]
I still get the same behaviour (native image build fails due to JapaneseImperialCalender)...
